version: '{build}'
skip_tags: true
clone_depth: 1
environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk11
      fast_finish: true
os: Windows Server 2012
install:
  - cmd: SET MAVEN_OPTS=-Xmx1g
  - cmd: SET JAVA_OPTS=-Xmx1g
  - cmd: mvn --version
  - cmd: java -version
build_script:
  - mvn package --batch-mode -DskipTests -Dmaven.javadoc.skip -Dmatsim.preferLocalDtds=true --fail-at-end -Dsource.skip -Dassembly.skipAssembly=true
# test_script:
#   - mvn test
cache:
  - C:\Users\appveyor\.m2 -> pom.xml
